### PR TITLE
Document attributes

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/60)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-tab.html, line 73 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60#-KwiMetezdR4qyUsx3Wx:-KwiMetf4LhITU5Ds68a:bvy41hi) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9a6fbd890cd9bae484faf1b2fd56333c252a33ce/vaadin-tab.html#L73)):*
> ```HTML
>        * Attribute  | Description | Part name
>        * -----------|-------------|------------
>        * `vertical` | Set to a disabled text field | :host
> ```

Disabled text-field???

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60)*

**Comment by tomivirkki** [comment]
*[vaadin-tabs.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60#-KwiMlwwv5kbMX6uqzLk:-KwiMlwwv5kbMX6uqzLl:bvy41hi) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9a6fbd890cd9bae484faf1b2fd56333c252a33ce/vaadin-tabs.html#L153)):*
> ```HTML
>        * Attribute  | Description | Part name
>        * -----------|-------------|------------
>        * `vertical` | Set to a disabled text field | :host
> ```

Disabled text-field???

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60)*

**Comment by tomivirkki** [comment]
*[vaadin-tab.html, line 74 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60#-KwiMrWTfHyBy_3R3tDG:-KwiMrWTfHyBy_3R3tDH:b-bdfk7o) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9a6fbd890cd9bae484faf1b2fd56333c252a33ce/vaadin-tab.html#L74)):*
> ```HTML
>        * -----------|-------------|------------
>        * `vertical` | Set to a disabled text field | :host
>        * `overflow` | It's set to `start`, `end`, none or both, based on whether there are scrollable items. | :host
> ```

I'm not following. Do the individual tabs have `overflow` attribute?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60)*

**Comment by tomivirkki** [comment]
Also remember to add the general styling link

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60#-:-KwiMzRNCWXUMHsTolPu:bxx9fc)*

**Comment by manolo** [comment]
Done

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-tab.html, line 73 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60#-KwiMetezdR4qyUsx3Wx:-KwiNQrjIVy9xEBeh3Zi:b-oawvna) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9a6fbd890cd9bae484faf1b2fd56333c252a33ce/vaadin-tab.html#L73)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Disabled text-field???
</blockquote></details>

Sorry, didn't save last changes in atom before committing. Done

---

*[vaadin-tabs.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60#-KwiMlwwv5kbMX6uqzLk:-KwiNl0CgnWI--MRWZ0u:b-896fix) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9a6fbd890cd9bae484faf1b2fd56333c252a33ce/vaadin-tabs.html#L153)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Disabled text-field???
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60#-:-KwiNxQFWyu4rBWw90YL:bb6un1j)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-tab.html, line 74 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60#-KwiMrWTfHyBy_3R3tDG:-KwiO52h3CdrDc5vm7Wv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9a6fbd890cd9bae484faf1b2fd56333c252a33ce/vaadin-tab.html#L74)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I'm not following. Do the individual tabs have `overflow` attribute?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60)*

**Comment by tomivirkki** [comment]
:lgtm_strong: 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/60#-:-Kwif-uxrDbChVv2dykG:b-uwkowd)*

**Pull request merged**
