### PR TITLE
Add _scrollToItem

### LINKED ISSUE #25: Selected tab should be scrolled visible
If the selected tab is outside of the tabs visible area, adjust the scroll position so that it becomes visible.

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #25 

Add _moveItemToScrollerEdge, move selected tabs to edge of the scroller, navigate with the same rule

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/28)

### CODE REVIEW

**Comment by manolo** [comment]
I don't see any reason for this PR breaking performance tests. Not sure if we should decrease the threshold or jus disabled them. We might try to run tests at  least locally with and without this changes

I miss some tests for this code

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-list-mixin.html, line 147 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-Kw53JRrgpY1vPUatY4o:-Kw53JRrgpY1vPUatY4p:b-61mwx) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/57ac14505648471d41a1214b6da1571738fe87d3/vaadin-list-mixin.html#L147)):*
> ```HTML
>       items[idx] && items.forEach(e => e.selected = e === items[idx]);
>       this._moveItemToScrollerEdge(idx);
>       this._setFocusable(idx);
> ```

I'm not sure that we want to move the tabindex to the selected item. what @jouni  thinks ?  
I would remove these line and the block focusing the selected below .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-:-Kw52tyWtZHavlFBtaQ3:b6bsgbo)*

**Comment by limonte** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-list-mixin.html, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-Kw53dJntbo26FQAzTqn:-Kw53dJntbo26FQAzTqo:bwhut5v) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/57ac14505648471d41a1214b6da1571738fe87d3/vaadin-list-mixin.html#L124)):*
> ```HTML
>     }
> 
>     _moveItemToScrollerEdge(idx) {
> ```

1. Add explanation comment about this method
2. Rename it not to contain the "Edge" word, it's confusing. `_scrollToItem()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28)*

**Comment by limonte** [comment]
Try to make the PR title more useful as well.

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-list-mixin.html, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-Kw53dJntbo26FQAzTqn:-Kw5AgRv8bzH9Je-6JSS:b-vptkgi) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/57ac14505648471d41a1214b6da1571738fe87d3/vaadin-list-mixin.html#L124)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

1. Add explanation comment about this method
2. Rename it not to contain the "Edge" word, it's confusing. `_scrollToItem()`?
</blockquote></details>

It means move scroll to item, but also, move the item to the edge of the scroll. I understood when I read, but I agree that might be confusing with the browser name.
scrollToItem makes sense because it's the action to do. Then add a comment saying that at the same time the item is moved to the edge for better ux.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28)*

**Comment by YuriyVaadin** [comment]
I have changed the name of the method, added comments and tests. Previously there was a random error with performance test, seems to be working correctly now.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-list-mixin.html, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-Kw53dJntbo26FQAzTqn:-Kw9J1B4_BNLAFd6eiCr:b-6ke5dt) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/57ac14505648471d41a1214b6da1571738fe87d3/vaadin-list-mixin.html#L124)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It means move scroll to item, but also, move the item to the edge of the scroll. I understood when I read, but I agree that might be confusing with the browser name.
scrollToItem makes sense because it's the action to do. Then add a comment saying that at the same time the item is moved to the edge for better ux.
</blockquote></details>

Have changed the name and added comment.

---

*[vaadin-list-mixin.html, line 147 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-Kw53JRrgpY1vPUatY4o:-Kw9JB-rIr8-NyWzyDDt:bidbnpn) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/57ac14505648471d41a1214b6da1571738fe87d3/vaadin-list-mixin.html#L147)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I'm not sure that we want to move the tabindex to the selected item. what @jouni  thinks ?  
I would remove these line and the block focusing the selected below .

</blockquote></details>

So in this case on selecting a new tab for end user it will look like focused one (scrolling done and styles applied), however it won't be focused and tabindexes will not change. On refocusing of the `vaadin-tabs` element itself user will be confused how the focus moves and how it is interconnected with selected value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-:-Kw9JsSyXRMTCr-y_JnL:b-8nm0ad)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-list-mixin.html, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-Kw53dJntbo26FQAzTqn:-Kw9_D9zrCGx67mYV37m:bl9ahxe) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/57ac14505648471d41a1214b6da1571738fe87d3/vaadin-list-mixin.html#L124)):*
> Scroll the item to the viewport so it will be displayed on the edge of it.

To me is clearer `Scroll the container to have the item by the edge of the viewport`

---

*[vaadin-list-mixin.html, line 147 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-Kw53JRrgpY1vPUatY4o:-Kw9_h8zka5MEDtA8snP:b-necy4j) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/57ac14505648471d41a1214b6da1571738fe87d3/vaadin-list-mixin.html#L147)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

So in this case on selecting a new tab for end user it will look like focused one (scrolling done and styles applied), however it won't be focused and tabindexes will not change. On refocusing of the `vaadin-tabs` element itself user will be confused how the focus moves and how it is interconnected with selected value.
</blockquote></details>

The point is that focus is not related with selected. For instance try to move the focus, then push tab and shift-tab, the focus goes back to latest visited item but not to the selected one. That is in this way in other components, but I'm not sure about the best UX, ping @jouni 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-list-mixin.html, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-Kw53dJntbo26FQAzTqn:-Kw9jLapP5tHVlaXirs1:b-a2ujfl) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/57ac14505648471d41a1214b6da1571738fe87d3/vaadin-list-mixin.html#L124)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

> Scroll the item to the viewport so it will be displayed on the edge of it.

To me is clearer `Scroll the container to have the item by the edge of the viewport`
</blockquote></details>

Changed.

---

*[vaadin-list-mixin.html, line 147 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-Kw53JRrgpY1vPUatY4o:-Kw9jMTfnTCOQNJ--l_7:b-62780m) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/57ac14505648471d41a1214b6da1571738fe87d3/vaadin-list-mixin.html#L147)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

The point is that focus is not related with selected. For instance try to move the focus, then push tab and shift-tab, the focus goes back to latest visited item but not to the selected one. That is in this way in other components, but I'm not sure about the best UX, ping @jouni 
</blockquote></details>

Removed. In case @jouni will confirm that we need it, will add in separated PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-:-Kw9npJAzC7o8Sa6Z_t_:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-:-Kw9oDpddoCEn1o4Wz6a:bnfp4nl)*

**Comment by jouni** [comment]
*[vaadin-list-mixin.html, line 147 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28#-Kw53JRrgpY1vPUatY4o:-Kw9aSpPqZ0rmTcD849q:b6pm472) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/57ac14505648471d41a1214b6da1571738fe87d3/vaadin-list-mixin.html#L147)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Removed. In case @jouni will confirm that we need it, will add in separated PR.
</blockquote></details>

I was about to say, that we should at least on the first render move the focus to the selected item.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/28)*

**Pull request merged**
