### PR TITLE
Use iron-icon instead of paper-item, demonstrate aria-label

### LINKED ISSUE #46: Replace paper elements
Should we replace paper elements with vaadin elements in 'Advance Examples' as there are at least two issues with those:

1. Default focus styles are applied for the paper elements. It can confuse the user.
1. In some rare cases tab is not selected when user clicks on it (probably produced by unintentional dragging/selection).

third_tab_ex

### PR DESCRIPTION
**Pull request by limonte**
Fixes #46

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/55)

### CODE REVIEW

**Comment by limonte** [comment]
Someone fucked up visual tests before me, failing build isn't related to this PR.

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo/tabs-advanced-demos.html, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/55#-KwG9k-Io3StCdlc8Typ:-KwG9k-JLT_FBqSuBEWd:b-e1g40v) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/78803211ed4c2fa8a27b24c18cbbcae2c0a09ac4/demo/tabs-advanced-demos.html#L62)):*
> ```HTML
>           </vaadin-tab>
>           <vaadin-tab>
>             <paper-icon-item tabindex="-1">
> ```

This demo was here intentionally to demonstrate that our component can be integrated with other item elements like paper which the community are familiar with.
To demonstrate a new use case, you just need to add a new tab, but not replacing this, since your use case is different.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/55)*

**Comment by tomivirkki** [comment]
*[demo/tabs-advanced-demos.html, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/55#-KwG9k-Io3StCdlc8Typ:-KwJVc0F1qjMWzuv7oRc:b-68tfkl) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/78803211ed4c2fa8a27b24c18cbbcae2c0a09ac4/demo/tabs-advanced-demos.html#L62)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This demo was here intentionally to demonstrate that our component can be integrated with other item elements like paper which the community are familiar with.
To demonstrate a new use case, you just need to add a new tab, but not replacing this, since your use case is different.
</blockquote></details>

I recall the original idea was to have paper-items in a separate demo (instead of mixing my-custom-items and paper-items in the same one). I understand that it feels weird to users that the items appear so different within the same nav.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/55)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/tabs-advanced-demos.html, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/55#-KwG9k-Io3StCdlc8Typ:-KwJzdEDiBcXQ6yW608Y:bmc6ujk) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9610d7f9d3da742c571bdbbf9094e02a2336b93b/demo/tabs-advanced-demos.html#L62)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I recall the original idea was to have paper-items in a separate demo (instead of mixing my-custom-items and paper-items in the same one). I understand that it feels weird to users that the items appear so different within the same nav.
</blockquote></details>

We are removing all paper- elements from our demos, there's a reason for that - different approaches in styling. UX participants were confused with styles of the paper-item.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/55)*

**Comment by manolo** [comment]
:lgtm_strong: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/55#-:-KwTnHcEEFKndLWim3jN:b-uwkowd)*

**Pull request merged**
