### PR TITLE
Fix equal width tabs for IE11

### LINKED ISSUE #85: Equal width tabs display incorrectly with IE11 when tabs element is justified center
Having
```html
<div style="display: flex; justify-content: center;">
<vaadin-tabs theme="equal-width-tabs">
  <vaadin-tab>Tab one</vaadin-tab>
  <vaadin-tab>Tab two with a longer title</vaadin-tab>
  <vaadin-tab>Tab three</vaadin-tab>
</vaadin-tabs>
</div>
```

IE11 shows content cut 
image

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #85

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/87)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/lumo/vaadin-tabs.html, line 172 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/87#-L7OZWVTISfGwBUldwfs:-L7OZWVUa4Pvrk3UEZjY:bjzr9a1) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/6a6121ca15339de2d1bdb64713d83dd61bf709d3/theme/lumo/vaadin-tabs.html#L172)):*
> ```HTML
> 
>       :host([theme~="equal-width-tabs"]) [part="tabs"] ::slotted(vaadin-tab) {
>         flex: 1 0 0;
> ```

BTW, I'm wondering if we should replace this with `flex: auto` in order to avoid this flex bug: https://github.com/philipwalton/flexbugs#flexbug-4

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/87)*

**Comment by tomivirkki** [comment]
*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L8WDLJgAVfh-NlCNYF0:-L8WDLJgAVfh-NlCNYF1:b4c2coh) (no related file):*
Please include a test that verifies the issue and the fix for it

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by samiheikki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L8WDLJgAVfh-NlCNYF0:-L8x18Bo-6QSk_apc43U:b-iw1p49) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Please include a test that verifies the issue and the fix for it
</blockquote></details>

Added test

---

*[theme/lumo/vaadin-tabs.html, line 172 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L7OZWVTISfGwBUldwfs:-L8x16qdBvOn8DvLxO0-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/6a6121ca15339de2d1bdb64713d83dd61bf709d3/theme/lumo/vaadin-tabs.html#L172)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW, I'm wondering if we should replace this with `flex: auto` in order to avoid this flex bug: https://github.com/philipwalton/flexbugs#flexbug-4
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L8WDLJgAVfh-NlCNYF0:-L9OgKRd0C4Ea55ajB1T:bg7igkv) (no related file):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Added test
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by tomivirkki** [comment]
This PR breaks the feature. Try with the code snippet attached to the [original issue](https://github.com/vaadin/vaadin-tabs/issues/85). This is how it's supposed to look like:
screenshot 2018-04-06 10 22 40

As you can see, the tabs have equal widths.

After applying the change in this PR, here's how it looks like:
screenshot 2018-04-06 10 22 59

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[theme/lumo/vaadin-tabs.html, line 172 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L7OZWVTISfGwBUldwfs:-L9jaW0r2tijgvyxubgl:b-daenk0) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/6a6121ca15339de2d1bdb64713d83dd61bf709d3/theme/lumo/vaadin-tabs.html#L172)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`auto` here does not work fine as @tomivirkki points.  It breaks the theme for all browsers. 
One solution working on all browsers seems to be:

```
        flex: 1;
        flex-shrink: 0;
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[theme/lumo/vaadin-tabs.html, line 172 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L7OZWVTISfGwBUldwfs:-L9jebqSB1UK-iApxebJ:bscmpkr) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/6a6121ca15339de2d1bdb64713d83dd61bf709d3/theme/lumo/vaadin-tabs.html#L172)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

`auto` here does not work fine as @tomivirkki points.  It breaks the theme for all browsers. 
One solution working on all browsers seems to be:

```
        flex: 1;
        flex-shrink: 0;
```
</blockquote></details>

@manolo makes sense. We might want to explicitly set `

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[theme/lumo/vaadin-tabs.html, line 172 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L7OZWVTISfGwBUldwfs:-L9jftE2DgGSU9CFKy4j:bfmejdf) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/6a6121ca15339de2d1bdb64713d83dd61bf709d3/theme/lumo/vaadin-tabs.html#L172)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

@manolo makes sense. We might want to explicitly set `
</blockquote></details>

oops. my comment was broken, I meant use `flex: 1 0 0%` as suggested here: https://github.com/philipwalton/flexbugs#workaround-3

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[theme/lumo/vaadin-tabs.html, line 172 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L7OZWVTISfGwBUldwfs:-L9jgVAO0cq9Twn2fSjB:bje68r3) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/6a6121ca15339de2d1bdb64713d83dd61bf709d3/theme/lumo/vaadin-tabs.html#L172)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

oops. my comment was broken, I meant use `flex: 1 0 0%` as suggested here: https://github.com/philipwalton/flexbugs#workaround-3
</blockquote></details>

My concern is that minifiers ruin the fix  as is mentioned in that workaround

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[theme/lumo/vaadin-tabs.html, line 172 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L7OZWVTISfGwBUldwfs:-L9jj8uM98OHdqUsdBr9:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/6a6121ca15339de2d1bdb64713d83dd61bf709d3/theme/lumo/vaadin-tabs.html#L172)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

OK discussed in person, feel free to go ahead with your solution.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L9jkWhvDbOMgqW2MDU5:-L9jkWhwBrsZsGwGrB1z:bdwladc) (no related file):*
Needs rebase to get tests passing, because of the Travis config change introduced in 522668e

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L9jkWhvDbOMgqW2MDU5:-L9k30v0BX6JKHO27KPJ:b9x2p3v) (no related file):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Needs rebase to get tests passing, because of the Travis config change introduced in 522668e
</blockquote></details>

Rebased

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L9jkWhvDbOMgqW2MDU5:-L9n-q6w9rfDpdIYEIBc:bpfzpnj) (no related file):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Rebased
</blockquote></details>

This patch seems not fixing the original issue. The screenshot in issue displays already `tabs` of the same size. The problem here is that in IE11 the width of the entire `vaadin-tabs` element is smaller than in other browsers as it's shown in these screenshots:

```
<body>
  <div style="display: flex; justify-content: center;">
    <vaadin-tabs theme="equal-width-tabs" style="width: 100%">
      <vaadin-tab>Tab one</vaadin-tab>
      <vaadin-tab>Tab two with a longer title</vaadin-tab>
      <vaadin-tab>Tab three</vaadin-tab>
    </vaadin-tabs>
  </div>
</body>
```



When setting `flex: 1 0 0` it also breaks Edge in the same way



But either `flex: 1 0 0%` or `flex: 1; flex-shrink: 0;` makes Edge work, but still does not fix IE11



---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L9jkWhvDbOMgqW2MDU5:-L9nAqrJ8ofxqh_aiRX_:btxmcql) (no related file):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This patch seems not fixing the original issue. The screenshot in issue displays already `tabs` of the same size. The problem here is that in IE11 the width of the entire `vaadin-tabs` element is smaller than in other browsers as it's shown in these screenshots:

```
<body>
  <div style="display: flex; justify-content: center;">
    <vaadin-tabs theme="equal-width-tabs" style="width: 100%">
      <vaadin-tab>Tab one</vaadin-tab>
      <vaadin-tab>Tab two with a longer title</vaadin-tab>
      <vaadin-tab>Tab three</vaadin-tab>
    </vaadin-tabs>
  </div>
</body>
```



When setting `flex: 1 0 0` it also breaks Edge in the same way



But either `flex: 1 0 0%` or `flex: 1; flex-shrink: 0;` makes Edge work, but still does not fix IE11


</blockquote></details>

It seems that the only way to make look the same in all browsers is by specifying some width to the `vaadin-tabs` when `theme=equal-width-tabs`.
One option is to set `width: 100%`, another option is to set some flex value, or just leave as it is and developer needs to specify some width. What @jouni thinks?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L9jkWhvDbOMgqW2MDU5:-L9nJ4-m8KZw4tJIHGgC:b9c4ka9) (no related file):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It seems that the only way to make look the same in all browsers is by specifying some width to the `vaadin-tabs` when `theme=equal-width-tabs`.
One option is to set `width: 100%`, another option is to set some flex value, or just leave as it is and developer needs to specify some width. What @jouni thinks?


</blockquote></details>

BTW @manolo have you tried `flex: 1 0 0.001%;`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L9jkWhvDbOMgqW2MDU5:-L9nKKNd7OaUFuv_i3CG:blidjmx) (no related file):*
> flex: 1 0 0.001%

@platosha does not change anything

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L9jkWhvDbOMgqW2MDU5:-L9nKxw50a5qqYcysQbD:b-3iwt1) (no related file):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

> flex: 1 0 0.001%

@platosha does not change anything
</blockquote></details>

@manolo and with px: `flex: 1 0 0.001px;`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L9jkWhvDbOMgqW2MDU5:-L9nMU7C7b0xeEDq0Zn7:bb7hvse) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

@manolo and with px: `flex: 1 0 0.001px;`?
</blockquote></details>

@manolo ah, now I’ve noticed that you mention the width of the tabs container, yeah this could be the issue. In that case `[part="tabs"] { width: 100%; }` might help as a fix.

Note that if we do that, we should also set `flex: none;` to buttons to prevent them from shrinking.

That is a bit safer than having `width: 100%;` on the host, as we have more control over parts styling, while the host styles are exposed in the parent scope.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L9jkWhvDbOMgqW2MDU5:-L9npRP9D0JH59DF0Gsu:b-ty1wkk) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

@manolo ah, now I’ve noticed that you mention the width of the tabs container, yeah this could be the issue. In that case `[part="tabs"] { width: 100%; }` might help as a fix.

Note that if we do that, we should also set `flex: none;` to buttons to prevent them from shrinking.

That is a bit safer than having `width: 100%;` on the host, as we have more control over parts styling, while the host styles are exposed in the parent scope.
</blockquote></details>

setting `width: 100%` to `tabs` part does not help

Discussed in private, we agreed on set `flex: auto` to the host for this `theme` so as the computed width is the same for all browsers.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-:-L9o9l2i6H_Jeb-aUakf:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[theme/lumo/vaadin-tabs.html, line 172 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-L7OZWVTISfGwBUldwfs:-L9oFCMrDmhAVivG867n:bho6yx7) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/6a6121ca15339de2d1bdb64713d83dd61bf709d3/theme/lumo/vaadin-tabs.html#L172)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done
</blockquote></details>

finally came with `0%` seems quite safe as it's mentioned in several articles

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87)*

**Comment by tomivirkki** [comment]
:lgtm: Although the original example doesn't look the same by default on IE and Chrome

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-tabs/87#-:-L9ynbIvCkMDjcytdWsr:brrc5gb)*

**Pull request merged**
