### PR TITLE
Rename `vertical` to `orientation`

### PR DESCRIPTION
**Pull request by manolo**
Connected to https://github.com/vaadin/vaadin-core/issues/105

Note: depends on a list-mixin branch in order to pass CI, but will be  depend on `1.3.0` before merge

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/61)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-KwyLHvrAFuzpPm8FQE7:-KwyLHvrAFuzpPm8FQE8:b-waoohw) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9919b54fea4a232cd3bc570640a81bc436546117/bower.json#L30)):*
> ```JSON
>     "iron-resizable-behavior": "^2.0.0",
>     "vaadin-themable-mixin": "^1.1.4",
>     "vaadin-list-mixin": "vaadin/vaadin-list-mixin#fix/selected-string"
> ```

Need a release?

---

*[vaadin-tabs.html, line 215 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-KwyMKarFKP_dtEWzdVi:-KwyMKasgdfj0WSyKmKL:b737bao) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9919b54fea4a232cd3bc570640a81bc436546117/vaadin-tabs.html#L215)):*
> ```HTML
> 
>         get _scrollOffset() {
>           return this.orientation != 'horizontal' ? this._scrollerElement.offsetHeight : this._scrollerElement.offsetWidth;
> ```

`this.orientation != 'horizontal'` is the same as `this._vertical`, right?

Would be safer to redefine `get _vertical()` in this class (or use `this.orientation !== 'horizontal'` everywhere) than relying on a private function from another module. If it, for example, gets cleaned up in some release, -tabs would break.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61)*

**Comment by tomivirkki** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-tabs.html, line 177 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-KwyPJDV-9n40rfQ0D3h:-KwyPJDV-9n40rfQ0D3i:brce1py) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9919b54fea4a232cd3bc570640a81bc436546117/vaadin-tabs.html#L177)):*
> ```HTML
>              * Set tabs disposition. Possible values are `horizontal|vertical`
>              */
>             orientation: {
> ```

Define the property type

---

*[vaadin-tabs.html, line 185 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-KwyPGBOhaaTfhOPJEc0:-KwyPGBPeG7HYWktZlVu:b-oejxx8) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9919b54fea4a232cd3bc570640a81bc436546117/vaadin-tabs.html#L185)):*
> ```HTML
>              */
>             selected: {
>               value: 0
> ```

Define the property type. Otherwise the attribute might deserialize as wrong type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61)*

**Comment by manolo** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[bower.json, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-KwyLHvrAFuzpPm8FQE7:-KwyvdeAqo6-I3H5MZnZ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9919b54fea4a232cd3bc570640a81bc436546117/bower.json#L30)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Need a release?
</blockquote></details>

Done.

---

*[vaadin-tabs.html, line 177 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-KwyPJDV-9n40rfQ0D3h:-KwyveUyKnJKxWLaTSbd:b-896fix) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9919b54fea4a232cd3bc570640a81bc436546117/vaadin-tabs.html#L177)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Define the property type
</blockquote></details>

Done.

---

*[vaadin-tabs.html, line 185 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-KwyPGBOhaaTfhOPJEc0:-Kwyvf4Dm4z4k-Pyi9Tf:b-ku74k8) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9919b54fea4a232cd3bc570640a81bc436546117/vaadin-tabs.html#L185)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Define the property type. Otherwise the attribute might deserialize as wrong type.
</blockquote></details>

Shouldn't be necessary since polymer inheritance takes care of some properties defined in super like observers, but otherwise it passes a string to super, and that converts to a number, I think is a bug in polymer but need to research more.

Anyways, it's better to define here, so as documentation also shows the type and not only the default value.
Done.

---

*[vaadin-tabs.html, line 215 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-KwyMKarFKP_dtEWzdVi:-KwyvkiyPc4EmD9GZJ36:b-896fix) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9919b54fea4a232cd3bc570640a81bc436546117/vaadin-tabs.html#L215)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`this.orientation != 'horizontal'` is the same as `this._vertical`, right?

Would be safer to redefine `get _vertical()` in this class (or use `this.orientation !== 'horizontal'` everywhere) than relying on a private function from another module. If it, for example, gets cleaned up in some release, -tabs would break.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61)*

**Comment by tomivirkki** [comment]
*[vaadin-tabs.html, line 215 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-KwyMKarFKP_dtEWzdVi:-Kx7DvbAVfrAyUXn2xbM:bgrk06l) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9919b54fea4a232cd3bc570640a81bc436546117/vaadin-tabs.html#L215)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. Still using a private function of a dependency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61)*

**Comment by tomivirkki** [comment]
*[vaadin-tab.html, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-Kx7caTc6AoILcU0s6R_:-Kx7caTc6AoILcU0s6Ra:bm4eoqv) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/c31b982ba1c4d13b8312cb7dfaec51af6d37ed35/vaadin-tab.html#L75)):*
> ```HTML
>        * Attribute  | Description | Part name
>        * -----------|-------------|------------
>        * `disabled` | Set to a disabled text field | :host
> ```

text-field -> tab

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61)*

**Comment by tomivirkki** [comment]
There are still tests that use the old API (`vertical`). Really strange that they can pass even when the API doesn't exist anymore.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-:-Kx7dmmkTyDj5zUU-JP1:byu8z6d)*

**Comment by YuriyVaadin** [comment]
Reviewed 9 of 12 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61)*

**Comment by manolo** [comment]
Review status: 11 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-tab.html, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-Kx7caTc6AoILcU0s6R_:-Kx8GylLarTX_V0V4Vpv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/c31b982ba1c4d13b8312cb7dfaec51af6d37ed35/vaadin-tab.html#L75)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

text-field -> tab
</blockquote></details>

Done.

---

*[vaadin-tabs.html, line 215 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-KwyMKarFKP_dtEWzdVi:-Kx8H-GvLZ6berZd4Wo5:b2lr1m3) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/9919b54fea4a232cd3bc570640a81bc436546117/vaadin-tabs.html#L215)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Not done. Still using a private function of a dependency.
</blockquote></details>

Updated dependency, so as now we are using a protected property.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61)*

**Comment by manolo** [comment]
Review status: 11 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[test/scrollable-tabs.html, line 86 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-Kx8QJ4qCT8-LATG47-T:-Kx8QJ4qCT8-LATG47-U:be3qppr) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/c6984e7dc1fcc896a1084c03043a7b7be24a54b8/test/scrollable-tabs.html#L86)):*
> ```HTML
>         nav._focus(5);
>         // Check the scroller is scrolled vertically
>         expect(nav._scrollerElement.scrollTop).not.to.be.equal(0);
> ```

In order to be sure that this test passes you need to do the same assertion but in false before moving the arrow, so code should be:

```
        expect(nav._scrollerElement.getBoundingClientRect().bottom).not.to.be.closeTo(nav._navItems[7].getBoundingClientRect().bottom, 1);
arrowDown(nav);     expect(nav._scrollerElement.getBoundingClientRect().bottom).to.be.closeTo(nav._navItems[7].getBoundingClientRect().bottom, 1);


```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61)*

**Comment by manolo** [comment]
Review status: 11 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/scrollable-tabs.html, line 86 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-Kx8QJ4qCT8-LATG47-T:-Kx8Wt2ZSfNDhAm4ocVL:b-29r0ws) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/c6984e7dc1fcc896a1084c03043a7b7be24a54b8/test/scrollable-tabs.html#L86)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

In order to be sure that this test passes you need to do the same assertion but in false before moving the arrow, so code should be:

```
        expect(nav._scrollerElement.getBoundingClientRect().bottom).not.to.be.closeTo(nav._navItems[7].getBoundingClientRect().bottom, 1);
arrowDown(nav);     expect(nav._scrollerElement.getBoundingClientRect().bottom).to.be.closeTo(nav._navItems[7].getBoundingClientRect().bottom, 1);


```
</blockquote></details>

Updated tests, so as assertion checks that the scroll actually moves.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 7 of 12 files at r1, 3 of 4 files at r2, 2 of 2 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/61#-:-KxC1z-E7F1mkRqbLwZq:bnfp4nl)*

**Pull request merged**
