### PR TITLE
Default theme

### PR DESCRIPTION
**Pull request by jouni**
Remove unnecessary wrapping div element (`.vaadin-tabs`).

Add a themable part for the tab container element (`tabs`). This is
partly required by polyfilled browsers so that `::slotted` selectors
work, and themes can target those.

Call `_updateOverflow` after the first render has been done for the
child tab elements as well, so any potential overflow will be caught.

Remove unnecessary wrapping `part=“button”` from the tab element.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/29)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-tabs.html, line 81 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/29#-Kw3utJFLtZDuN3miXl4:-Kw3utJFLtZDuN3miXl5:byjfra9) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/7a8908574b6bfb3064e064db0b331fa20b1aa089/vaadin-tabs.html#L81)):*
> ```HTML
>       :host([vertical]) [part="forward-button"]::after {
>         content: '▼';
>       }
> ```

This probably breaks visual tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/29)*

**Comment by YuriyVaadin** [comment]
There is a problem with visual tests, otherwise the PR :lgtm: 

---

Reviewed 2 of 2 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/29#-:-Kw42AAWldYnaCkUvSJw:b-nbym1h)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 2 of 13 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/29#-:-Kw45q9DU20iyeOcXJMJ:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 2 of 13 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/29#-:-Kw46A8QSO3m8Lxn3ILn:bnfp4nl)*

**Pull request merged**
