### PR TITLE
Scroll in advance

### LINKED ISSUE #45: Edge case: tabs inside tab
When putting `vaadin-tabs` inside `vaadin-tab` it is working, but produces errors from the mixin that should be fixed.

screen shot 2017-10-12 at 12 57 50

### LINKED ISSUE #47: One item in advance
While navigating with arrow keys there should be a possibility to see upcoming tab, so we will definitely be able to see if there are more items and to recognise when we are at the beginning or at the end of `vaadin-tabs`

**Current behaviour:**
before_horizontal
before_vertical

**Desired behaviour:**
after_horizontal
after_vertical

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #47 
Fixes #45 

**Before:**
before_horizontal
before_vertical

**After:**
after_horizontal
after_vertical

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/42)

### CODE REVIEW

**Comment by jouni** [comment]
LGTM 👍

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[vaadin-list-mixin.html, line 149 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-KwG281ffAxLgU_gjevg:-KwG281ffAxLgU_gjevh:bkgkixd) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/1a97a68391367dd8f7eb461c1d6ad719485fc438/vaadin-list-mixin.html#L149)):*
> ```HTML
> 
>       return scrollerRect[side] > prevItemRect[side] && prevItemRect[side] - scrollerRect[side];
>     }
> ```

These two blocks above, is the typical case of 'this code smells to duplicated'. You can put one over the other and nothing changes but 3 chars. Please unify the code by adding a boolean or an increment (+1/-1) parameter

---

*[vaadin-list-mixin.html, line 161 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-KwG3aAvKSvnabT2f5Xf:-KwG3aAvKSvnabT2f5Xg:bpki2vm) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/1a97a68391367dd8f7eb461c1d6ad719485fc438/vaadin-list-mixin.html#L161)):*
> ```HTML
>       var scrollDistance;
> 
>       if (!this.vertical) {
> ```

all this set of `if` statements, should set the scrollDistance, then you can have just one line of `this._scroll` at the end.

---

*[test/scrollable-tabs.html, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-KwG47xEKoGD87gp1NLX:-KwG47xEKoGD87gp1NLY:b2vnb50) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/ac486cf2650252607ee6e72c5cbe353c04a40916/test/scrollable-tabs.html#L19)):*
> ```HTML
>         <vaadin-tab>Bar</vaadin-tab>
>         <separator>___</separator>
>         <vaadin-tab disabled>Baz</vaadin-tab>
> ```

why do yo remove the disabled item, it was intentionally left there, in order to check that focus loop code skips it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-list-mixin.html, line 149 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-KwG281ffAxLgU_gjevg:-KwJ_HWENEMgIFuxOGbB:b-wnzex2) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/1a97a68391367dd8f7eb461c1d6ad719485fc438/vaadin-list-mixin.html#L149)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

These two blocks above, is the typical case of 'this code smells to duplicated'. You can put one over the other and nothing changes but 3 chars. Please unify the code by adding a boolean or an increment (+1/-1) parameter
</blockquote></details>

Now there is only one `_getScrollOffsetOfTheItem` method

---

*[vaadin-list-mixin.html, line 161 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-KwG3aAvKSvnabT2f5Xf:-KwJ_L5aUn1zW6H757xO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/1a97a68391367dd8f7eb461c1d6ad719485fc438/vaadin-list-mixin.html#L161)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

all this set of `if` statements, should set the scrollDistance, then you can have just one line of `this._scroll` at the end.
</blockquote></details>

Done.

---

*[test/scrollable-tabs.html, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-KwG47xEKoGD87gp1NLX:-KwJ_Lw08NoOhiJ4X0Yc:bqmjwcz) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/ac486cf2650252607ee6e72c5cbe353c04a40916/test/scrollable-tabs.html#L19)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why do yo remove the disabled item, it was intentionally left there, in order to check that focus loop code skips it.
</blockquote></details>

Added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42)*

**Comment by tomivirkki** [comment]
*[vaadin-list-mixin.html, line 161 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-KwG3aAvKSvnabT2f5Xf:-KwJsFNGWFdJe5FRNFNT:bto8qhq) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/1a97a68391367dd8f7eb461c1d6ad719485fc438/vaadin-list-mixin.html#L161)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Would this feature work with following these changes? https://github.com/vaadin/vaadin-tabs/compare/feature/scroll-in-advance...scroll-in-advance-opt?expand=1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-list-mixin.html, line 161 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-KwG3aAvKSvnabT2f5Xf:-KwJu1UQiCPeXnfPUifJ:b5tpncj) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/1a97a68391367dd8f7eb461c1d6ad719485fc438/vaadin-list-mixin.html#L161)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Would this feature work with following these changes? https://github.com/vaadin/vaadin-tabs/compare/feature/scroll-in-advance...scroll-in-advance-opt?expand=1
</blockquote></details>

Yes, it's awesome and covers all of the cases. Merged

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-:-KwJwa0mGSYb4cQct1MX:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-:-KwKAZEVpzcE__Svd5-q:bnfp4nl)*

**Comment by manolo** [comment]
Apparently, you need to fix broken tests

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-:-KwTqS210pAB3O-eDwW7:b-f7d5k4)*

**Comment by tomivirkki** [comment]
Tests fixed (to pass in IE also)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-:-KwTw9ypZb8Sf2c9bglh:b-qvqjvt)*

**Comment by tomivirkki** [comment]
Reviewed 5 of 5 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42)*

**Comment by limonte** [comment]
> Tests fixed (to pass in IE also)

:rocket: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/42#-:-KwZ6-iR9XnydV7gJy1j:blzg84b)*

**Pull request merged**
