### PR TITLE
Add workaround for tabindex in advanced demo

### LINKED ISSUE #24: Tab doesn't working properly in the third item of the latest advanced example
When the third item of the latest advanced example is focused and I press <kbd>Tab</kbd> something weird happens: 
recorded

Expected: the next focusable element (the Copy button) is focused.

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #24 

Implement workaround proposed by @jouni

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/27)

### CODE REVIEW

**Comment by jouni** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/27#-:-Kw-jbuBahinmjm-DB_-:bnfp4nl)*

**Comment by jouni** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/27)*

**Comment by jouni** [comment]
Oh man, reviewable is still too confusing for me to use :D

**Comment by tomivirkki** [comment]
:lgtm: Please fix merge conflict

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/27#-:-Kw-sqSRsdalgQ9vuCqT:b-3pic2c)*

**Pull request merged**
