### PR TITLE
Added support for centered horizontal tabs.

### PR DESCRIPTION
**Pull request by tamasnet**
I'd like to use centered tabs in a Flow app, getting this into the official web component seems to be the straightest path. Thanks for your consideration!

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/99)

### CODE REVIEW

**Comment by limonte** [comment]
Thanks for your contribution, @tamasnet! I personally like this enhancement. There are some small things to amend in the code, but before going into details I'd like to get a green light from @jouni and @tomivirkki about the new API. Any objections on introducing it?

**Comment by jouni** [comment]
A centered theme variant sounds alright. Is it indeed incompatible with scrolling? I would assume that scrolling should still work if the tabs overflow the container (the tabs would in effect become left-aligned when that happens).

**Comment by limonte** [comment]
>  I would assume that scrolling should still work if the tabs overflow the container

That's correct, the horizontal scrolling will work.

**Comment by jouni** [comment]
I’m not really sure what’s unclear here. I said this change looks alright to me and asked if scrolling could be made to work. Apparently there are some issues with that, so I think we can skip that requirement for now, and worry about it later.

Also, I assumed someone from the team would provide instructions how to modify the code. I think this should be a “theme variant”, not a built-in attribute/property, i.e. `<vaadin-tabs theme="centered">`. So remove the property and docs, and move the CSS to `theme/lumo/vaadin-tabs.html` instead and fix the selector from `[centered]` to `[theme~="centered"]`. You should also add an example of it to `demo/tabs-lumo-theme-demos.html`.

**Comment by YuriyVaadin** [comment]
@tamasnet, Thank you very much for your contribution!
I will take care of the updates requested by Jouni in separate branch.

**Comment by YuriyVaadin** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/99)*

**Pull request merged**
