### PR TITLE
Rename vaadin-nav -> vaadin-tabs

### PR DESCRIPTION
**Pull request by manolo**
Connected to #3

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/23)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 56 of 56 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/23#-:-KvzxDd2M7cbQ5yG-_NW:bnfp4nl)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[test/performance/config.json, line 2 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/23#-KvzxyEB2G0peYN9jzEx:-KvzxyEB2G0peYN9jzEy:b-81bj2q) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/df3c7f5746af0bba57005d15547d8209a5140455/test/performance/config.json#L2)):*
> ```JSON
> [
>   {"name": "index.html", "threshold": 0.75}
> ```

Any idea why the performance score decreased?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/23)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/performance/config.json, line 2 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/23#-KvzxyEB2G0peYN9jzEx:-Kw-9VCBIunx4oIvREVb:bqf7p87) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/df3c7f5746af0bba57005d15547d8209a5140455/test/performance/config.json#L2)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Any idea why the performance score decreased?
</blockquote></details>

In my computer I din't appreciate any decrease, I run tests before and after renaming. 
There is a random failure when it was 0.85, that is better lowering the value.
Probably we should disable these performance tests in all our components, I don't see any advantage on having them, since we don't rely on them, we don't have any actions when they fail but restart the build

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/23)*

**Comment by jouni** [comment]
> we don't have any actions when they fail but restart the build

In case of a big jump in the score, I hope you investigate what caused it. Right? The purpose of these tests is to catch major regressions, and also make you continuously consider performance as one of the major features of the elements!

**Comment by manolo** [comment]
The problem is that those tests are not reliable at all. So any pass or failure does not guarantees anything, that the reason why we don't pay any attention to it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/23#-:-Kw-eD4j3MYplAq1Xb1s:b-lbamgo)*

**Comment by jouni** [comment]
Well, that sounds like an issue you should resolve some way or another (make them reliable or get rid of them).

**Comment by limonte** [comment]
Agree with Manolo, the current implementation of perf tests is unreliable and in fact useless. I'm okay with dropping the perf test from this component as well as from other components.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/performance/config.json, line 2 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/23#-KvzxyEB2G0peYN9jzEx:-Kw-iFFQ9kOxxDrvEOSV:bsxb4ky) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/df3c7f5746af0bba57005d15547d8209a5140455/test/performance/config.json#L2)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

In my computer I din't appreciate any decrease, I run tests before and after renaming. 
There is a random failure when it was 0.85, that is better lowering the value.
Probably we should disable these performance tests in all our components, I don't see any advantage on having them, since we don't rely on them, we don't have any actions when they fail but restart the build

</blockquote></details>

works-on-my-machine (c)

Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/23#-:-Kw-iiO7Num1TTWJcepk:b-1uwky0)*

**Pull request merged**
