### PR TITLE
Enable visual tests

### PR DESCRIPTION
**Pull request by samiheikki**
Connects to https://github.com/vaadin/components-team-tasks/issues/314

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/98)

### CODE REVIEW

**Comment by manolo** [comment]
:lgtm_cancel:   a couple of tests fail randomly. I updated them and also failing, probably related with the transition when focusing the item take a look to screenshots in my commit in github comparing with previous screenshots

---

Review status: 19 of 21 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/98#-:-LD7l90F-DRLVrPMCA2X:b-ppwucm)*

**Comment by samiheikki** [comment]
Yeah, I tried fixing it with this https://github.com/vaadin/vaadin-tabs/blob/e26273fc00c9eab95906a9121cc3004fd96212a4/test/visual/test.js#L22 but that did not seem to work either. I'll continue investigation tomorrow

**Comment by samiheikki** [comment]
@manolo Fixed now

**Comment by manolo** [comment]
Well done! :lgtm_strong: 

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/98#-:-LDBQjtwExCgCWRUivzD:b-6vrjok)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 17 of 21 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/98#-:-LDBv28C8jX5VCr1zEO1:bnfp4nl)*

**Pull request merged**
