### PR TITLE
fix: only add vaadin-tab elements to items

### LINKED ISSUE #150: [4.x] Non-selectable items are now included in the vaadin-tabs "items" array
### Description
`vaadin-tabs` no longer [filters out](https://github.com/vaadin/vaadin-list-mixin/blob/e29947115fd6cb1cddd3bdcdebfed6c43a19d8ba/vaadin-list-mixin.html#L116) non-VaadinItemMixin items. This causes items like `<hr>` and other non-list items it be included in the `items` array. This can cause `selected` highlighting to be off from the correct element.

### Expected outcome
`vaadin-tabs` should filter out non-selectable items such as `<hr>`, etc.

### Actual outcome
`vaadin-tabs` includes all elements in its `items` array.

I was able to use this code with 3.x:
```
__onRouteChanged(e) {
  const tabList = this.shadowRoot.getElementById('navTabs'); // A vaadin-tabs element
  if (tabList) {
    tabList.selected = Array.from(tabList.querySelectorAll('vaadin-tab')).findIndex(
        (tab) => (tab.querySelector('a').pathname === e['detail'].location.pathname));
  }
}
```

I can change the code to work if I just search through all `items`, but I'm not sure if that's a BC break you want or not:
```
__onRouteChanged(e) {
  const tabList = this.shadowRoot.getElementById('navTabs'); // A vaadin-tabs element
  if (tabList) {
    tabList.selected = Array.from(tabList.items).findIndex(
        (tab) => (tab.querySelector('a') && tab.querySelector('a').pathname === e['detail'].location.pathname));
  }
}
```

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #150

### CODE REVIEW

**Comment by tomivirkki** [comment]
Hmm...shouldn't this rather filter all children by `child instanceOf VaadinTab` [similarly to what the previous major did](https://github.com/vaadin/vaadin-list-mixin/blob/master/vaadin-list-mixin.html#L117)? New Tabs would ignore VaadinTab extensions that have a tag name different from "vaadin-tab" (not sure if this is a big problem).

**Comment by web-padawan** [comment]
Anyone who wants to extend `VaadinTab` is free to also override `_filterItems` method.

We can re-introduce this check though. There is already [hasSelectedStateMixin](https://github.com/vaadin/component-mixins/blob/d5d3947b7ab0c2c6bb69e9ef46eda7cb0510f958/packages/selected-state-mixin/selected-state-mixin.ts#L21) that can be used for this purpose. Would it be better to use that here? @tomivirkki WDYT?

**Comment by moderndeveloperllc** [comment]
@web-padawan You are doing something like that here:
https://github.com/vaadin/component-mixins/blob/master/packages/single-selection-mixin/single-selection-mixin.ts#L16-L23

Makes sense to be consistent I guess? JM2C

**Comment by web-padawan** [comment]
@moderndeveloperllc actually, it might be good idea to export that function from there.

**Comment by web-padawan** [comment]
Submitted https://github.com/vaadin/component-mixins/issues/43 to fix that.

**Pull request merged**
