### PR TITLE
Checking scrollPosition to be more than 0

### LINKED ISSUE #63: overflow="start" state should not be applied when “over-scrolling” on iOS
On iOS, if the tabs are in the initial position, and you try to scroll more to left (swipe right), the `overflow="start"` state is applied.

Instead of checking for `!= 0` we should check for `> 0` here: https://github.com/vaadin/vaadin-tabs/blob/86487d576a606a28c95814cd8bd5f4266407f012/vaadin-tabs.html#L234

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #63 

Change to checking `scrollPosition` to be more than 0

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/64)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/64)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/64#-:-KyL_-BtVPxMn4zxpMYo:bnfp4nl)*

**Comment by tomivirkki** [comment]
Can this be tested?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/64#-:-KyL_JgGqbjTAzzpQXDA:b-buo2)*

**Comment by manolo** [comment]
@tomivirkki  Added the test. 

:lgtm: 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/64#-:-KyafSVr2JoYLcOdbYi2:b-vebauz)*

**Comment by tomivirkki** [comment]
Nice! :lgtm: 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/64#-:-Kyb4rJVVDkk_2gWgVTY:bfd61qr)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/64)*

**Pull request merged**
