### PR TITLE
iOS momentum scrolling

### LINKED ISSUE #50: iOS scrolling issue
On IPhone we do not have a momentum scrolling for `vertical` layout: it stacked at the moment of touch ends.

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #50 

Add -webkit-overflow-scrolling to enable momentum scrolling in vertical layout

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-tabs/52)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/52#-:-KwFFtDA4QX-ikMse8lE:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-tabs.html, line 87 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/52#-KwFLkaYAyjWdfBWgsHZ:-KwFLkaYAyjWdfBWgsH_:b-4kvxhc) ([raw file](https://github.com/vaadin/vaadin-tabs/blob/4af487e79dd033273a336a92d1dc397e742d89df/vaadin-tabs.html#L87)):*
> ```HTML
>         height: 100%;
>         overflow-y: auto;
>         -webkit-overflow-scrolling: touch;
> ```

Preferred fix would be to have the common CSS rule in a common style block:
```
[part="tabs"] {
  -webkit-overflow-scrolling: touch;
}
```
Not a blocker

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/52#-:-KwFLy-7RMSuIYv86cQx:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/52)*

**Comment by manolo** [comment]
Visual are broken for some commits ago, updating screenshots. 

---

Reviewed 1 of 1 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/52#-:-KwFOp4BtfddYmGUpJxV:b4wyl71)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-tabs/52#-:-KwG0GnTIoA6AG6g7orq:bnfp4nl)*

**Pull request merged**
